TARGET_SIZE = (256, 256)
INPUT_SHAPE = (256, 256)
IMG_SIZE    = (768, 768)
DATA_PATH   = '../input/airbus-ship-detection/'
TRAIN_PATH  = './data/train_df.csv'
TEST_PATH   = './data/valid_df.csv'
EPOCHS      = 25
BATCH_SIZE  = 48
momentum    = 0.8